# Generated by Django 4.2.3 on 2023-07-09 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('option_one', models.CharField(max_length=50)),
                ('option_two', models.CharField(max_length=50)),
                ('option_three', models.CharField(max_length=50)),
                ('option_count_one', models.IntegerField(default=0)),
                ('option_count_two', models.IntegerField(default=0)),
                ('option_count_three', models.IntegerField(default=0)),
            ],
        ),
    ]
