# Generated by Django 4.2.3 on 2023-07-09 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='option_count_five',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='poll',
            name='option_count_four',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='poll',
            name='option_five',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='poll',
            name='option_four',
            field=models.CharField(default='', max_length=50),
        ),
    ]
