# Generated by Django 4.2.3 on 2023-07-10 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_question_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rate',
            name='date',
        ),
        migrations.RemoveField(
            model_name='rate',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='rate',
            name='text',
        ),
        migrations.AddField(
            model_name='rate',
            name='rate_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rate',
            name='rate_1_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rate',
            name='rate_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rate',
            name='rate_2_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rate',
            name='rate_3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rate',
            name='rate_3_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rate',
            name='rate_4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rate',
            name='rate_4_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rate',
            name='rate_5',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rate',
            name='rate_5_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rate',
            name='question',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
