# Generated by Django 4.2.3 on 2023-07-10 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_rate_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rate',
            old_name='rate_1',
            new_name='rate_five',
        ),
        migrations.RenameField(
            model_name='rate',
            old_name='rate_2',
            new_name='rate_four',
        ),
        migrations.RenameField(
            model_name='rate',
            old_name='rate_3',
            new_name='rate_one',
        ),
        migrations.RenameField(
            model_name='rate',
            old_name='rate_4',
            new_name='rate_three',
        ),
        migrations.RenameField(
            model_name='rate',
            old_name='rate_5',
            new_name='rate_two',
        ),
    ]
