# Generated by Django 4.2.3 on 2023-07-17 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_rate_1_rate_rate_five_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('post_time', models.DateField()),
                ('time_stamp', models.DateField(auto_now_add=True, null=True)),
                ('Is_active', models.BooleanField()),
                ('Is_permanent', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='poll',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.entity'),
        ),
    ]
