# Generated by Django 4.2.3 on 2023-07-17 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_entity_alter_poll_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='Is_active',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='Is_permanent',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='post_time',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='time_stamp',
        ),
    ]
