# Generated by Django 4.2.3 on 2023-07-25 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rating_delete_rate_entity_rate_question_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_question', models.TextField(default='', max_length=50)),
            ],
        ),
    ]
