# Generated by Django 4.2.3 on 2023-07-25 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_entity_rate_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rate_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.rate'),
        ),
    ]
