# Generated by Django 4.2.3 on 2023-07-26 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_rating_rate_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rate_question',
            field=models.TextField(default='', max_length=100),
        ),
    ]
